### ISSUE TITLE
Small delay when playing a sound for the first time

### ISSUE THREAD

**Issue by mr-flannery** [adamcichy/SwiftySound#8]
Hey, first of all thanks for your work, really neat wrapper for playing sounds!

I'm building a metronome and I noticed that there is a small delay when playing a sound for the first time (or more specific: when calling play() the first time on either the Sound class or a Sound object). 
Currently I circumvent this issue by playing a sound and immediately stopping it in my viewDidLoad().

If you need more information, drop me a message. Cheers!

**Comment by adamcichy** [comment]
Hi @mr-flannery,

I'm glad that you sound SwiftySound useful.

I have implemented a `prepare` method which calls `prepareToPlay` method of `AVAudioPlayer` under the hood. This might help you but from my experience it does not do much. That's why I decided not to implement it initially. But you might want to try it and see if it helps in your case. If not, I would just stick to your workaround.
